// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Announcement struct {
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type Assignment struct {
	ID          string  `json:"id"`
	ClassroomID string  `json:"classroomId"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	DueDate     *string `json:"dueDate,omitempty"`
	TotalPoints *int    `json:"totalPoints,omitempty"`
}

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Classroom struct {
	ID            string          `json:"id"`
	CourseID      string          `json:"courseId"`
	Name          string          `json:"name"`
	Semester      string          `json:"semester"`
	Instructor    *User           `json:"instructor,omitempty"`
	Students      []*User         `json:"students,omitempty"`
	Tas           []*User         `json:"tas,omitempty"`
	Modules       []*Module       `json:"modules,omitempty"`
	Announcements []*Announcement `json:"announcements,omitempty"`
	Assignments   []*Assignment   `json:"assignments,omitempty"`
}

type Course struct {
	ID          string  `json:"id"`
	CourseCode  string  `json:"courseCode"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Credits     int     `json:"credits"`
	Instructor  *User   `json:"instructor,omitempty"`
}

type CreateAssignmentInput struct {
	ClassroomID string  `json:"classroomId"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	DueDate     *string `json:"dueDate,omitempty"`
	TotalPoints int     `json:"totalPoints"`
}

type CreateCourseInput struct {
	CourseCode      string   `json:"courseCode"`
	Name            string   `json:"name"`
	Description     *string  `json:"description,omitempty"`
	Credits         int      `json:"credits"`
	InstructorID    string   `json:"instructorId"`
	SemesterOffered *string  `json:"semesterOffered,omitempty"`
	CourseCap       *int     `json:"courseCap,omitempty"`
	PrerequisiteIds []string `json:"prerequisiteIds,omitempty"`
}

type CreateUserInput struct {
	Email             string                  `json:"email"`
	Password          string                  `json:"password"`
	Role              string                  `json:"role"`
	StudentProfile    *StudentProfileInput    `json:"studentProfile,omitempty"`
	InstructorProfile *InstructorProfileInput `json:"instructorProfile,omitempty"`
}

type GradeSubmissionInput struct {
	SubmissionID string `json:"submissionId"`
	Grade        int    `json:"grade"`
}

type InstructorProfileInput struct {
	FullName   string  `json:"fullName"`
	EmployeeID string  `json:"employeeId"`
	Department *string `json:"department,omitempty"`
}

type Module struct {
	Title     string `json:"title"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Registration struct {
	CourseID string  `json:"courseID"`
	Semester string  `json:"semester"`
	Course   *Course `json:"course,omitempty"`
}

type StudentProfileInput struct {
	FullName string  `json:"fullName"`
	RollNo   string  `json:"rollNo"`
	Branch   *string `json:"branch,omitempty"`
}

type Submission struct {
	ID           string `json:"id"`
	AssignmentID string `json:"assignmentId"`
	Student      *User  `json:"student"`
	Content      string `json:"content"`
	SubmittedAt  string `json:"submittedAt"`
	Grade        *int   `json:"grade,omitempty"`
	GradedBy     *User  `json:"gradedBy,omitempty"`
}

type SubmitWorkInput struct {
	AssignmentID string `json:"assignmentId"`
	Content      string `json:"content"`
}

type User struct {
	ID       string  `json:"id"`
	Email    string  `json:"email"`
	Role     string  `json:"role"`
	FullName *string `json:"fullName,omitempty"`
}
