// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Course struct {
	ID          string  `json:"id"`
	CourseCode  string  `json:"courseCode"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Credits     int     `json:"credits"`
	Instructor  *User   `json:"instructor,omitempty"`
}

type CreateCourseInput struct {
	CourseCode      string   `json:"courseCode"`
	Name            string   `json:"name"`
	Description     *string  `json:"description,omitempty"`
	Credits         int      `json:"credits"`
	InstructorID    string   `json:"instructorId"`
	SemesterOffered *string  `json:"semesterOffered,omitempty"`
	CourseCap       *int     `json:"courseCap,omitempty"`
	PrerequisiteIds []string `json:"prerequisiteIds,omitempty"`
}

type CreateUserInput struct {
	Email             string                  `json:"email"`
	Password          string                  `json:"password"`
	Role              string                  `json:"role"`
	StudentProfile    *StudentProfileInput    `json:"studentProfile,omitempty"`
	InstructorProfile *InstructorProfileInput `json:"instructorProfile,omitempty"`
}

type InstructorProfileInput struct {
	FullName   string  `json:"fullName"`
	EmployeeID string  `json:"employeeId"`
	Department *string `json:"department,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Registration struct {
	CourseID string  `json:"courseID"`
	Semester string  `json:"semester"`
	Course   *Course `json:"course,omitempty"`
}

type StudentProfileInput struct {
	FullName string  `json:"fullName"`
	RollNo   string  `json:"rollNo"`
	Branch   *string `json:"branch,omitempty"`
}

type User struct {
	ID       string  `json:"id"`
	Email    string  `json:"email"`
	Role     string  `json:"role"`
	FullName *string `json:"fullName,omitempty"`
}
